tiene(bulbasaur, tipo, planta).
tiene(bulbasaur, tipo, veneno).
tiene(ivysaur, tipo, planta).
tiene(ivysaur, tipo, veneno).
tiene(venusaur, tipo, planta).
tiene(venusaur, tipo, veneno).
tiene(charmander, tipo, fuego).
tiene(charmeleon, tipo, fuego).
tiene(charizard, tipo, fuego).
tiene(squirtle, tipo, agua).
tiene(wartortle, tipo, agua).
tiene(blastoise, tipo, agua).
tiene(caterpie, tipo, bicho).
tiene(metapod, tipo, bicho).
tiene(butterfree, tipo, bicho).
tiene(butterfree, tipo, volador).
tiene(weedle, tipo, bicho).
tiene(weedle, tipo, veneno).
tiene(kakuna, tipo, bicho).
tiene(kakuna, tipo, veneno).
tiene(beedrill, tipo, bicho).
tiene(beedrill, tipo, veneno).
tiene(pidgey, tipo, normal).
tiene(pidgey, tipo, volador).
tiene(pidgeotto, tipo, normal).
tiene(pidgeotto, tipo, volador).
tiene(pidgeot, tipo, normal).
tiene(pidgeot, tipo, volador).
tiene(rattata, tipo, normal).
tiene(raticate, tipo, normal).
tiene(spearow, tipo, normal).
tiene(spearow, tipo, volador).
tiene(fearow, tipo, normal).
tiene(fearow, tipo, volador).
tiene(ekans, tipo, veneno).
tiene(arbok, tipo, veneno).
tiene(pikachu, tipo, electrico).
tiene(raichu, tipo, electrico).
tiene(sandshrew, tipo, tierra).
tiene(sandslash, tipo, tierra).
tiene(nidoran, tipo, veneno).
tiene(nidorina, tipo, veneno).
tiene(nidoqueen, tipo, veneno).
tiene(nidoqueen, tipo, tierra).
tiene(nidoran, tipo, veneno).
tiene(nidorino, tipo, veneno).
tiene(nidoking, tipo, veneno).
tiene(nidoking, tipo, tierra).
tiene(clefairy, tipo, hada).
tiene(clefable, tipo, hada).
tiene(vulpix, tipo, fuego).
tiene(ninetales, tipo, fuego).
tiene(jigglypuff, tipo, normal).
tiene(jigglypuff, tipo, hada).
tiene(wigglytuff, tipo, normal).
tiene(wigglytuff, tipo, hada).
tiene(zubat, tipo, veneno).
tiene(zubat, tipo, volador).
tiene(golbat, tipo, veneno).
tiene(golbat, tipo, volador).
tiene(oddish, tipo, planta).
tiene(oddish, tipo, veneno).
tiene(gloom, tipo, planta).
tiene(gloom, tipo, veneno).
tiene(vileplume, tipo, planta).
tiene(vileplume, tipo, veneno).
tiene(paras, tipo, bicho).
tiene(paras, tipo, planta).
tiene(parasect, tipo, bicho).
tiene(parasect, tipo, planta).
tiene(venonat, tipo, bicho).
tiene(venonat, tipo, veneno).
tiene(venomoth, tipo, bicho).
tiene(venomoth, tipo, veneno).
tiene(diglett, tipo, tierra).
tiene(dugtrio, tipo, tierra).
tiene(meowth, tipo, normal).
tiene(persian, tipo, normal).
tiene(psyduck, tipo, agua).
tiene(golduck, tipo, agua).
tiene(mankey, tipo, lucha).
tiene(primeape, tipo, lucha).
tiene(growlithe, tipo, fuego).
tiene(arcanine, tipo, fuego).
tiene(poliwag, tipo, agua).
tiene(poliwhirl, tipo, agua).
tiene(poliwrath, tipo, agua).
tiene(poliwrath, tipo, lucha).
tiene(abra, tipo, psiquico).
tiene(kadabra, tipo, psiquico).
tiene(alakazam, tipo, psiquico).
tiene(machop, tipo, lucha).
tiene(machoke, tipo, lucha).
tiene(machamp, tipo, lucha).
tiene(bellsprout, tipo, planta).
tiene(bellsprout, tipo, veneno).
tiene(weepinbell, tipo, planta).
tiene(weepinbell, tipo, veneno).
tiene(victreebel, tipo, planta).
tiene(victreebel, tipo, veneno).
tiene(tentacool, tipo, agua).
tiene(tentacool, tipo, veneno).
tiene(tentacruel, tipo, agua).
tiene(tentacruel, tipo, veneno).
tiene(geodude, tipo, roca).
tiene(geodude, tipo, tierra).
tiene(graveler, tipo, roca).
tiene(graveler, tipo, tierra).
tiene(golem, tipo, roca).
tiene(golem, tipo, tierra).
tiene(ponyta, tipo, fuego).
tiene(rapidash, tipo, fuego).
tiene(slowpoke, tipo, agua).
tiene(slowpoke, tipo, psiquico).
tiene(slowbro, tipo, agua).
tiene(slowbro, tipo, psiquico).
tiene(magnemite, tipo, electrico).
tiene(magnemite, tipo, acero).
tiene(magneton, tipo, electrico).
tiene(magneton, tipo, acero).
tiene(farfetchd, tipo, normal).
tiene(farfetchd, tipo, volador).
tiene(doduo, tipo, normal).
tiene(doduo, tipo, volador).
tiene(dodrio, tipo, normal).
tiene(dodrio, tipo, volador).
tiene(seel, tipo, agua).
tiene(dewgong, tipo, agua).
tiene(dewgong, tipo, hielo).
tiene(grimer, tipo, veneno).
tiene(muk, tipo, veneno).
tiene(shellder, tipo, agua).
tiene(cloyster, tipo, agua).
tiene(cloyster, tipo, hielo).
tiene(gastly, tipo, fantasma).
tiene(gastly, tipo, veneno).
tiene(haunter, tipo, fantasma).
tiene(haunter, tipo, veneno).
tiene(gengar, tipo, fantasma).
tiene(gengar, tipo, veneno).
tiene(onix, tipo, roca).
tiene(onix, tipo, tierra).
tiene(drowzee, tipo, psiquico).
tiene(hypno, tipo, psiquico).
tiene(krabby, tipo, agua).
tiene(kingler, tipo, agua).
tiene(voltorb, tipo, electrico).
tiene(electrode, tipo, electrico).
tiene(exeggcute, tipo, planta).
tiene(exeggcute, tipo, psiquico).
tiene(exeggutor, tipo, planta).
tiene(exeggutor, tipo, psiquico).
tiene(cubone, tipo, tierra).
tiene(marowak, tipo, tierra).
tiene(hitmonlee, tipo, lucha).
tiene(hitmonchan, tipo, lucha).
tiene(lickitung, tipo, normal).
tiene(koffing, tipo, veneno).
tiene(weezing, tipo, veneno).
tiene(rhyhorn, tipo, tierra).
tiene(rhyhorn, tipo, roca).
tiene(rhydon, tipo, tierra).
tiene(rhydon, tipo, roca).
tiene(chansey, tipo, normal).
tiene(tangela, tipo, planta).
tiene(kangaskhan, tipo, normal).
tiene(horsea, tipo, agua).
tiene(seadra, tipo, agua).
tiene(goldeen, tipo, agua).
tiene(seaking, tipo, agua).
tiene(staryu, tipo, agua).
tiene(starmie, tipo, agua).
tiene(starmie, tipo, psiquico).
tiene(mr_mime, tipo, psiquico).
tiene(mr_mime, tipo, hada).
tiene(scyther, tipo, bicho).
tiene(scyther, tipo, volador).
tiene(jynx, tipo, hielo).
tiene(jynx, tipo, psiquico).
tiene(electabuzz, tipo, electrico).
tiene(magmar, tipo, fuego).
tiene(pinsir, tipo, bicho).
tiene(tauros, tipo, normal).
tiene(magikarp, tipo, agua).
tiene(gyarados, tipo, agua).
tiene(gyarados, tipo, volador).
tiene(lapras, tipo, agua).
tiene(lapras, tipo, hielo).
tiene(ditto, tipo, normal).
tiene(eevee, tipo, normal).
tiene(vaporeon, tipo, agua).
tiene(jolteon, tipo, electrico).
tiene(flareon, tipo, fuego).
tiene(porygon, tipo, normal).
tiene(omanyte, tipo, roca).
tiene(omanyte, tipo, agua).
tiene(omastar, tipo, roca).
tiene(omastar, tipo, agua).
tiene(kabuto, tipo, roca).
tiene(kabuto, tipo, agua).
tiene(kabutops, tipo, roca).
tiene(kabutops, tipo, agua).
tiene(aerodactyl, tipo, roca).
tiene(aerodactyl, tipo, volador).
tiene(snorlax, tipo, normal).
tiene(articuno, tipo, hielo).
tiene(articuno, tipo, volador).
tiene(zapdos, tipo, electrico).
tiene(zapdos, tipo, volador).
tiene(moltres, tipo, fuego).
tiene(moltres, tipo, volador).
tiene(dratini, tipo, dragon).
tiene(dragonair, tipo, dragon).
tiene(dragonite, tipo, dragon).
tiene(dragonite, tipo, volador).
tiene(mewtwo, tipo, psiquico).
tiene(mew, tipo, psiquico).

es_tipo_acero(X):-tiene(X, tipo, acero).
es_tipo_agua(X):-tiene(X, tipo, agua).
es_tipo_bicho(X):-tiene(X, tipo, bicho).
es_tipo_dragon(X):-tiene(X, tipo, dragon).
es_tipo_electrico(X):-tiene(X, tipo, electrico).
es_tipo_fantasma(X):-tiene(X, tipo, fantasma).
es_tipo_fuego(X):-tiene(X, tipo, fuego).
es_tipo_hada(X):-tiene(X, tipo, hada).
es_tipo_hielo(X):-tiene(X, tipo, hielo).
es_tipo_lucha(X):-tiene(X, tipo, lucha).
es_tipo_normal(X):-tiene(X, tipo, normal).
es_tipo_planta(X):-tiene(X, tipo, planta).
es_tipo_psiquico(X):-tiene(X, tipo, psiquico).
es_tipo_roca(X):-tiene(X, tipo, roca).
es_tipo_siniestro(X):-tiene(X, tipo, siniestro).
es_tipo_tierra(X):-tiene(X, tipo, tierra).
es_tipo_veneno(X):-tiene(X, tipo, veneno).
es_tipo_volador(X):-tiene(X, tipo, volador).
es_tipo_incognito(X):-tiene(X, tipo, incognito).

es_tipo_elemental(X):-es_tipo_acero(X)
 ; es_tipo_agua(X)
 ; es_tipo_bicho(X)
 ; es_tipo_dragon(X)
 ; es_tipo_electrico(X)
 ; es_tipo_fantasma(X)
 ; es_tipo_fuego(X)
 ; es_tipo_hada(X)
 ; es_tipo_hielo(X)
 ; es_tipo_lucha(X)
 ; es_tipo_normal(X)
 ; es_tipo_planta(X)
 ; es_tipo_psiquico(X)
 ; es_tipo_roca(X)
 ; es_tipo_siniestro(X)
 ; es_tipo_tierra(X)
 ; es_tipo_veneno(X)
 ; es_tipo_volador(X).
