tipo(bulbasaur, planta).
tipo(bulbasaur, veneno).
tipo(ivysaur, planta).
tipo(ivysaur, veneno).
tipo(venusaur, planta).
tipo(venusaur, veneno).
tipo(charmander, fuego).
tipo(charmeleon, fuego).
tipo(charizard, fuego).
tipo(squirtle, agua).
tipo(wartortle, agua).
tipo(blastoise, agua).
tipo(caterpie, bicho).
tipo(metapod, bicho).
tipo(butterfree, bicho).
tipo(butterfree, volador).
tipo(weedle, bicho).
tipo(weedle, veneno).
tipo(kakuna, bicho).
tipo(kakuna, veneno).
tipo(beedrill, bicho).
tipo(beedrill, veneno).
tipo(pidgey, normal).
tipo(pidgey, volador).
tipo(pidgeotto, normal).
tipo(pidgeotto, volador).
tipo(pidgeot, normal).
tipo(pidgeot, volador).
tipo(rattata, normal).
tipo(raticate, normal).
tipo(spearow, normal).
tipo(spearow, volador).
tipo(fearow, normal).
tipo(fearow, volador).
tipo(ekans, veneno).
tipo(arbok, veneno).
tipo(pikachu, electrico).
tipo(raichu, electrico).
tipo(sandshrew, tierra).
tipo(sandslash, tierra).
tipo(nidoran, veneno).
tipo(nidorina, veneno).
tipo(nidoqueen, veneno).
tipo(nidoqueen, tierra).
tipo(nidoran, veneno).
tipo(nidorino, veneno).
tipo(nidoking, veneno).
tipo(nidoking, tierra).
tipo(clefairy, hada).
tipo(clefable, hada).
tipo(vulpix, fuego).
tipo(ninetales, fuego).
tipo(jigglypuff, normal).
tipo(jigglypuff, hada).
tipo(wigglytuff, normal).
tipo(wigglytuff, hada).
tipo(zubat, veneno).
tipo(zubat, volador).
tipo(golbat, veneno).
tipo(golbat, volador).
tipo(oddish, planta).
tipo(oddish, veneno).
tipo(gloom, planta).
tipo(gloom, veneno).
tipo(vileplume, planta).
tipo(vileplume, veneno).
tipo(paras, bicho).
tipo(paras, planta).
tipo(parasect, bicho).
tipo(parasect, planta).
tipo(venonat, bicho).
tipo(venonat, veneno).
tipo(venomoth, bicho).
tipo(venomoth, veneno).
tipo(diglett, tierra).
tipo(dugtrio, tierra).
tipo(meowth, normal).
tipo(persian, normal).
tipo(psyduck, agua).
tipo(golduck, agua).
tipo(mankey, lucha).
tipo(primeape, lucha).
tipo(growlithe, fuego).
tipo(arcanine, fuego).
tipo(poliwag, agua).
tipo(poliwhirl, agua).
tipo(poliwrath, agua).
tipo(poliwrath, lucha).
tipo(abra, psiquico).
tipo(kadabra, psiquico).
tipo(alakazam, psiquico).
tipo(machop, lucha).
tipo(machoke, lucha).
tipo(machamp, lucha).
tipo(bellsprout, planta).
tipo(bellsprout, veneno).
tipo(weepinbell, planta).
tipo(weepinbell, veneno).
tipo(victreebel, planta).
tipo(victreebel, veneno).
tipo(tentacool, agua).
tipo(tentacool, veneno).
tipo(tentacruel, agua).
tipo(tentacruel, veneno).
tipo(geodude, roca).
tipo(geodude, tierra).
tipo(graveler, roca).
tipo(graveler, tierra).
tipo(golem, roca).
tipo(golem, tierra).
tipo(ponyta, fuego).
tipo(rapidash, fuego).
tipo(slowpoke, agua).
tipo(slowpoke, psiquico).
tipo(slowbro, agua).
tipo(slowbro, psiquico).
tipo(magnemite, electrico).
tipo(magnemite, acero).
tipo(magneton, electrico).
tipo(magneton, acero).
tipo(farfetchd, normal).
tipo(farfetchd, volador).
tipo(doduo, normal).
tipo(doduo, volador).
tipo(dodrio, normal).
tipo(dodrio, volador).
tipo(seel, agua).
tipo(dewgong, agua).
tipo(dewgong, hielo).
tipo(grimer, veneno).
tipo(muk, veneno).
tipo(shellder, agua).
tipo(cloyster, agua).
tipo(cloyster, hielo).
tipo(gastly, fantasma).
tipo(gastly, veneno).
tipo(haunter, fantasma).
tipo(haunter, veneno).
tipo(gengar, fantasma).
tipo(gengar, veneno).
tipo(onix, roca).
tipo(onix, tierra).
tipo(drowzee, psiquico).
tipo(hypno, psiquico).
tipo(krabby, agua).
tipo(kingler, agua).
tipo(voltorb, electrico).
tipo(electrode, electrico).
tipo(exeggcute, planta).
tipo(exeggcute, psiquico).
tipo(exeggutor, planta).
tipo(exeggutor, psiquico).
tipo(cubone, tierra).
tipo(marowak, tierra).
tipo(hitmonlee, lucha).
tipo(hitmonchan, lucha).
tipo(lickitung, normal).
tipo(koffing, veneno).
tipo(weezing, veneno).
tipo(rhyhorn, tierra).
tipo(rhyhorn, roca).
tipo(rhydon, tierra).
tipo(rhydon, roca).
tipo(chansey, normal).
tipo(tangela, planta).
tipo(kangaskhan, normal).
tipo(horsea, agua).
tipo(seadra, agua).
tipo(goldeen, agua).
tipo(seaking, agua).
tipo(staryu, agua).
tipo(starmie, agua).
tipo(starmie, psiquico).
tipo(mr_mime, psiquico).
tipo(mr_mime, hada).
tipo(scyther, bicho).
tipo(scyther, volador).
tipo(jynx, hielo).
tipo(jynx, psiquico).
tipo(electabuzz, electrico).
tipo(magmar, fuego).
tipo(pinsir, bicho).
tipo(tauros, normal).
tipo(magikarp, agua).
tipo(gyarados, agua).
tipo(gyarados, volador).
tipo(lapras, agua).
tipo(lapras, hielo).
tipo(ditto, normal).
tipo(eevee, normal).
tipo(vaporeon, agua).
tipo(jolteon, electrico).
tipo(flareon, fuego).
tipo(porygon, normal).
tipo(omanyte, roca).
tipo(omanyte, agua).
tipo(omastar, roca).
tipo(omastar, agua).
tipo(kabuto, roca).
tipo(kabuto, agua).
tipo(kabutops, roca).
tipo(kabutops, agua).
tipo(aerodactyl, roca).
tipo(aerodactyl, volador).
tipo(snorlax, normal).
tipo(articuno, hielo).
tipo(articuno, volador).
tipo(zapdos, electrico).
tipo(zapdos, volador).
tipo(moltres, fuego).
tipo(moltres, volador).
tipo(dratini, dragon).
tipo(dragonair, dragon).
tipo(dragonite, dragon).
tipo(dragonite, volador).
tipo(mewtwo, psiquico).
tipo(mew, psiquico).

es_tipo_acero(X):-tipo(X, acero).
es_tipo_agua(X):-tipo(X, agua).
es_tipo_bicho(X):-tipo(X, bicho).
es_tipo_dragon(X):-tipo(X, dragon).
es_tipo_electrico(X):-tipo(X, electrico).
es_tipo_fantasma(X):-tipo(X, fantasma).
es_tipo_fuego(X):-tipo(X, fuego).
es_tipo_hada(X):-tipo(X, hada).
es_tipo_hielo(X):-tipo(X, hielo).
es_tipo_lucha(X):-tipo(X, lucha).
es_tipo_normal(X):-tipo(X, normal).
es_tipo_planta(X):-tipo(X, planta).
es_tipo_psiquico(X):-tipo(X, psiquico).
es_tipo_roca(X):-tipo(X, roca).
es_tipo_siniestro(X):-tipo(X, siniestro).
es_tipo_tierra(X):-tipo(X, tierra).
es_tipo_veneno(X):-tipo(X, veneno).
es_tipo_volador(X):-tipo(X, volador).
es_tipo_incognito(X):-tipo(X, incognito).

es_tipo_elemental(X):-es_tipo_acero(X)
 ; es_tipo_agua(X)
 ; es_tipo_bicho(X)
 ; es_tipo_dragon(X)
 ; es_tipo_electrico(X)
 ; es_tipo_fantasma(X)
 ; es_tipo_fuego(X)
 ; es_tipo_hada(X)
 ; es_tipo_hielo(X)
 ; es_tipo_lucha(X)
 ; es_tipo_normal(X)
 ; es_tipo_planta(X)
 ; es_tipo_psiquico(X)
 ; es_tipo_roca(X)
 ; es_tipo_siniestro(X)
 ; es_tipo_tierra(X)
 ; es_tipo_veneno(X)
 ; es_tipo_volador(X).
